#############################################################################
#
# makefile.due common settings for My-First-Dev-Board projects
#
# (c) Wouter van Ooijen (www.voti.nl) 2017
#
# This file is in the public domain.
#
#############################################################################

# SETTINGS FOR ARDUINO DUE PROJECTS
TARGET            := my_first_dev_board
SERIAL_PORT       ?= COM4
CONSOLE_BAUDRATE  := 2400

# DEFER TO THE MAKEFILE.LINK
include           $(RELATIVE)/Makefile.link
