#############################################################################
#
# makefile.due common settings for Arduino Due projects
#
# (c) Wouter van Ooijen (www.voti.nl) 2017
#
# This file is in the public domain.
#
#############################################################################

# SETTINGS FOR ARDUINO DUE PROJECTS
TARGET            := arduino_due

ifeq ($(OS),Windows_NT)
	SERIAL_PORT       ?= COM3
else
	SERIAL_PORT_DUE   ?= /dev/ttyACM0
	SERIAL_PORT_UNO   := /dev/ttyUSB0
endif

CONSOLE_BAUDRATE  := 115200

# DEFER TO THE MAKEFILE.LINK
include           $(RELATIVE)/Makefile.link
